export { changeSlideNext } from './slide/slideActions'
export { changeSlidePrev } from './slide/slideActions'
export { changePhotoNum,changePhotoNext,changePhotoPrev } from './photo/photoActions'
export { wayToMove } from './way/wayActions'
export { moveToDsc } from './move/moveAction'
export { moveToMain } from './move/moveAction'
export { moveUp } from './move3d/move3dAction'
export { moveDown } from './move3d/move3dAction'
export { lightAdd } from './light/lightActions'
export { lightSub } from './light/lightActions'
export { lightSet} from './light/lightActions'
export { scaleAdd,scaleSet,scaleSub } from './scale/scaleActions'
export {loadOn,loadOff} from './loading/loadingActions'
export {loadPhotoOn,loadPhotoOff} from './loadPhoto/loadPhotoActions'